# Generated by Django 4.0.6 on 2022-07-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcessImage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadResolutionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RenameModel(
            old_name='UploadImage',
            new_name='UploadLightImage',
        ),
    ]
